dag: true

env:
  BUILDKITE_AWS_STACK_BUCKET: "uber-web-monorepo/stacks"
  BUILDKITE_AWS_STACK_TEMPLATE_BUCKET: "uber-web-monorepo/stack-templates"
  BUILDKITE_VPC_ID: "vpc-0e304267bc7352e38"
  AWS_KEYPAIR: "web-code"

steps:
  - id: "lint"
    name: ":bash: Lint"
    command: .buildkite/steps/lint.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"

  - id: "bats-tests"
    name: ":bash: Unit tests"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      docker-compose#v2.1.0:
        run: unit-tests
        config: docker-compose.unit-tests.yml

  - id: "s3secrets-helper-linux-amd64"
    name: ":golang: :linux: s3secrets-helper-linux-amd64"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      docker#v3.7.0:
        image: "golang:1.15"
        mount-checkout: false
        volumes:
          - "./build:/build:rw"
          - "./plugins/secrets/s3secrets-helper:/s3secrets-helper:ro"
        workdir: /s3secrets-helper
        environment:
          - "GOOS=linux"
          - "GOARCH=amd64"
        command: ["go", "build", "-o", "/build/s3secrets-helper-linux-amd64"]
    artifact_paths:
      - build/s3secrets-helper-linux-amd64

  - id: "s3secrets-helper-linux-arm64"
    name: ":golang: :linux: s3secrets-helper-linux-arm64"
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    plugins:
      docker#v3.7.0:
        image: "golang:1.15"
        mount-checkout: false
        volumes:
          - "./build:/build:rw"
          - "./plugins/secrets/s3secrets-helper:/s3secrets-helper:ro"
        workdir: /s3secrets-helper
        environment:
          - "GOOS=linux"
          - "GOARCH=arm64"
        command: ["go", "build", "-o", "/build/s3secrets-helper-linux-arm64"]
    artifact_paths:
      - build/s3secrets-helper-linux-arm64

  - id: "packer-linux-amd64"
    name: ":packer: :linux: AMD64"
    command: .buildkite/steps/packer.sh linux
    timeout_in_minutes: 60
    retry: { automatic: { limit: 1 } }
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    depends_on:
      - "lint"
      - "bats-tests"
      - "s3secrets-helper-linux-amd64"

  - id: "launch-linux-amd64"
    name: ":cloudformation: :linux: AMD64 Launch"
    command: .buildkite/steps/launch.sh linux
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "build/aws-stack.yml"
    depends_on: "packer-linux-amd64"
    plugins:
      - ssh://gitolite@code.uber.internal/infra/uber-vault-buildkite-plugin#1.0.0:
          namespace: "buildkite"
          addr: "https://secret-gateway-production-phx.uber.internal:4130"
          path: "buildkite"
          method: "aws"
          role: "staging"
          groups:
            - name: "common"

  - id: "test-linux-amd64"
    name: ":cloudformation: :linux: AMD64 Test"
    command: "goss validate --format documentation"
    timeout_in_minutes: 5
    agents:
      stack: "buildkite-aws-stack-test-linux-amd64-${BUILDKITE_BUILD_NUMBER}"
      queue: "testqueue-linux-amd64-${BUILDKITE_BUILD_NUMBER}"
    depends_on: "launch-linux-amd64"

  - id: "packer-linux-arm64"
    name: ":packer: :linux: ARM64"
    command: .buildkite/steps/packer.sh linux arm64
    timeout_in_minutes: 60
    retry: { automatic: { limit: 1 } }
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    depends_on:
      - "lint"
      - "bats-tests"
      - "s3secrets-helper-linux-arm64"

  - id: "launch-linux-arm64"
    name: ":cloudformation: :linux: ARM64 Launch"
    command: .buildkite/steps/launch.sh linux arm64
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "build/aws-stack.yml"
    depends_on: "packer-linux-arm64"
    plugins:
      - ssh://gitolite@code.uber.internal/infra/uber-vault-buildkite-plugin#1.0.0:
          namespace: "buildkite"
          addr: "https://secret-gateway-production-phx.uber.internal:4130"
          path: "buildkite"
          method: "aws"
          role: "staging"
          groups:
            - name: "common"

  - id: "test-linux-arm64"
    name: ":cloudformation: :linux: ARM64 Test"
    command: "goss validate --format documentation"
    timeout_in_minutes: 5
    agents:
      stack: "buildkite-aws-stack-test-linux-arm64-${BUILDKITE_BUILD_NUMBER}"
      queue: "testqueue-linux-arm64-${BUILDKITE_BUILD_NUMBER}"
    depends_on: "launch-linux-arm64"

  - id: "create-mappings"
    name: ":cloudformation: 🗺️"
    command: .buildkite/steps/mappings.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    artifact_paths: "build/mappings.yml"
    depends_on:
      - "test-linux-amd64"
      - "test-linux-arm64"

  - id: "publish"
    name: ":cloudformation: :rocket:"
    command: .buildkite/steps/publish.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    concurrency_group: "aws-stack-publish"
    concurrency: 1
    artifact_paths: "build/*.yml"
    depends_on: "create-mappings"

  - id: "cleanup"
    name: "Cleanup"
    command: .buildkite/steps/cleanup.sh
    agents:
      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE}"
    depends_on: "publish"
